channels:
    - pytorch
name:
    dl-image-pytorch-cpu
dependencies:
    - cpuonly
    - imageio
    - jupyter
    - nb_conda
    - pip
    - pytorch
    - scikit-image
    - scikit-learn
    - tensorboard
    - torchvision
    - tqdm
    - pip:
        - cifar2png
